# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: 2
  timeout: 5000
  host: localhost
  encoding: unicode
  username: ror_test
  password: ror_test

development:
  <<: *default
  database: ror_development

test:
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  database: db/test.sqlite3

production:
  <<: *default
  database: ror_production
